-- Trainer and gym-leader team updates from the Yellow Legacy
-- disassembly (cRz-Shadows/Pokemon_Yellow_Legacy, data/trainers/
-- parties.asm).  Species are ROM constants resolved against the
-- player's imported data at load; only existing trainer classes
-- are patched, party indexes preserved.
return {
  trainers = {
    ["OPP_AGATHA"] = { parties = {
      { {level = 57, species = "GENGAR"}, {level = 58, species = "GOLBAT"}, {level = 57, species = "MAROWAK"}, {level = 58, species = "ARBOK"}, {level = 59, species = "GENGAR"} },
    } },
    ["OPP_BEAUTY"] = { parties = {
      { {level = 29, species = "TANGELA"}, {level = 29, species = "WEEPINBELL"}, {level = 29, species = "EXEGGCUTE"} },
      { {level = 30, species = "TANGELA"}, {level = 30, species = "IVYSAUR"} },
      { {level = 32, species = "VICTREEBEL"} },
      { {level = 28, species = "RATICATE"}, {level = 28, species = "NINETALES"}, {level = 28, species = "GLOOM"} },
      { {level = 30, species = "CLEFAIRY"}, {level = 30, species = "PERSIAN"} },
      { {level = 45, species = "SEAKING"} },
      { {level = 40, species = "CLOYSTER"}, {level = 40, species = "KINGLER"}, {level = 40, species = "CLOYSTER"} },
      { {level = 41, species = "POLIWHIRL"}, {level = 41, species = "SEAKING"} },
      { {level = 35, species = "GOLDUCK"}, {level = 35, species = "WIGGLYTUFF"} },
      { {level = 35, species = "IVYSAUR"}, {level = 35, species = "TANGELA"} },
      { {level = 33, species = "WEEPINBELL"}, {level = 33, species = "BELLSPROUT"}, {level = 33, species = "WEEPINBELL"} },
      { {level = 43, species = "GOLDUCK"}, {level = 43, species = "DEWGONG"}, {level = 43, species = "SEAKING"} },
      { {level = 46, species = "LAPRAS"} },
      { {level = 43, species = "DRAGONAIR"}, {level = 43, species = "GYARADOS"}, {level = 43, species = "SEADRA"} },
      { {level = 43, species = "BLASTOISE"}, {level = 43, species = "DEWGONG"}, {level = 43, species = "SLOWBRO"} },
    } },
    ["OPP_BIKER"] = { parties = {
      { {level = 29, species = "SHELLDER"}, {level = 29, species = "WEEZING"}, {level = 29, species = "CLOYSTER"} },
      { {level = 30, species = "SANDSLASH"}, {level = 30, species = "MACHOKE"} },
      { {level = 34, species = "SANDSLASH"}, {level = 34, species = "KOFFING"}, {level = 34, species = "SANDSLASH"}, {level = 34, species = "GRIMER"} },
      { {level = 34, species = "KOFFING"}, {level = 34, species = "GRIMER"}, {level = 36, species = "WEEZING"} },
      { {level = 29, species = "GRIMER"}, {level = 29, species = "BEEDRILL"} },
      { {level = 30, species = "WEEZING"} },
      { {level = 28, species = "GRIMER"}, {level = 28, species = "CHARMELEON"}, {level = 28, species = "RHYHORN"}, {level = 28, species = "GRIMER"} },
      { {level = 33, species = "WEEZING"}, {level = 33, species = "KOFFING"}, {level = 33, species = "WEEZING"} },
      { {level = 35, species = "MUK"} },
      { {level = 32, species = "ELECTRODE"}, {level = 32, species = "MAGNETON"} },
      { {level = 32, species = "WEEZING"}, {level = 32, species = "MUK"} },
      { {level = 30, species = "SANDSLASH"}, {level = 30, species = "KRABBY"}, {level = 30, species = "KOFFING"}, {level = 30, species = "KINGLER"} },
      { {level = 31, species = "BEEDRILL"}, {level = 31, species = "WEEZING"}, {level = 31, species = "BEEDRILL"} },
      { {level = 32, species = "HITMONCHAN"}, {level = 32, species = "GRIMER"}, {level = 32, species = "KOFFING"} },
      { {level = 32, species = "HITMONLEE"}, {level = 32, species = "MUK"} },
    } },
    ["OPP_BIRD_KEEPER"] = { parties = {
      { {level = 32, species = "FEAROW"}, {level = 32, species = "PIDGEOTTO"} },
      { {level = 28, species = "SPEAROW"}, {level = 28, species = "DODUO"}, {level = 28, species = "PIDGEY"}, {level = 28, species = "SPEAROW"}, {level = 28, species = "SPEAROW"} },
      { {level = 30, species = "PIDGEOTTO"}, {level = 30, species = "FEAROW"}, {level = 30, species = "PIDGEOTTO"}, {level = 30, species = "FEAROW"} },
      { {level = 33, species = "FARFETCHD"} },
      { {level = 31, species = "DODRIO"}, {level = 31, species = "FEAROW"} },
      { {level = 35, species = "PIDGEOTTO"}, {level = 35, species = "FARFETCHD"}, {level = 35, species = "DODRIO"}, {level = 35, species = "PIDGEOTTO"} },
      { {level = 36, species = "DODRIO"}, {level = 36, species = "PIDGEOT"} },
      { {level = 34, species = "PIDGEOTTO"}, {level = 34, species = "FEAROW"} },
      { {level = 36, species = "DODRIO"} },
      { {level = 32, species = "FARFETCHD"}, {level = 32, species = "DODUO"}, {level = 32, species = "FEAROW"} },
      { {level = 41, species = "FEAROW"}, {level = 41, species = "FEAROW"}, {level = 41, species = "PIDGEOT"} },
      { {level = 39, species = "PIDGEOTTO"}, {level = 39, species = "PIDGEOTTO"}, {level = 39, species = "PIDGEY"}, {level = 39, species = "PIDGEOTTO"} },
      { {level = 42, species = "FARFETCHD"}, {level = 42, species = "FEAROW"} },
      { {level = 33, species = "PIDGEY"}, {level = 33, species = "DODUO"}, {level = 33, species = "PIDGEOTTO"} },
      { {level = 31, species = "FARFETCHD"}, {level = 31, species = "SPEAROW"}, {level = 31, species = "PIDGEY"}, {level = 31, species = "FEAROW"} },
      { {level = 34, species = "FEAROW"}, {level = 34, species = "PIDGEOTTO"} },
      { {level = 32, species = "PIDGEOTTO"}, {level = 32, species = "DODUO"}, {level = 32, species = "FEAROW"} },
    } },
    ["OPP_BLACKBELT"] = { parties = {
      { {level = 37, species = "HITMONLEE"}, {level = 37, species = "HITMONCHAN"} },
      { {level = 31, species = "MANKEY"}, {level = 31, species = "MANKEY"}, {level = 31, species = "PRIMEAPE"} },
      { {level = 32, species = "MACHOP"}, {level = 32, species = "MACHOKE"} },
      { {level = 36, species = "PRIMEAPE"} },
      { {level = 31, species = "MACHOP"}, {level = 31, species = "MANKEY"}, {level = 31, species = "PRIMEAPE"} },
      { {level = 52, species = "POLIWRATH"}, {level = 52, species = "MACHOKE"} },
      { {level = 53, species = "MACHOKE"}, {level = 53, species = "HITMONLEE"} },
      { {level = 51, species = "HITMONLEE"}, {level = 51, species = "HITMONCHAN"}, {level = 51, species = "MACHOKE"} },
      { {level = 52, species = "POLIWRATH"}, {level = 52, species = "DODRIO"}, {level = 52, species = "MACHAMP"}, {level = 52, species = "PINSIR"} },
    } },
    ["OPP_BLAINE"] = { parties = {
      { {level = 52, species = "RAPIDASH"}, {level = 51, species = "CHARIZARD"}, {level = 51, species = "NINETALES"}, {level = 52, species = "ARCANINE"}, {level = 53, species = "MAGMAR"} },
    } },
    ["OPP_BRUNO"] = { parties = {
      { {level = 57, species = "HITMONCHAN"}, {level = 56, species = "POLIWRATH"}, {level = 57, species = "HITMONLEE"}, {level = 56, species = "ONIX"}, {level = 58, species = "MACHAMP"} },
    } },
    ["OPP_BUG_CATCHER"] = { parties = {
      { {level = 6, species = "CATERPIE"}, {level = 6, species = "WEEDLE"}, {level = 6, species = "CATERPIE"} },
      { {level = 7, species = "METAPOD"}, {level = 6, species = "CATERPIE"}, {level = 7, species = "KAKUNA"} },
      { {level = 8, species = "PINSIR"}, {level = 9, species = "METAPOD"} },
      { {level = 8, species = "METAPOD"}, {level = 8, species = "KAKUNA"}, {level = 10, species = "BUTTERFREE"} },
      { {level = 9, species = "WEEDLE"}, {level = 9, species = "KAKUNA"}, {level = 9, species = "CATERPIE"}, {level = 9, species = "METAPOD"} },
      { {level = 9, species = "METAPOD"}, {level = 9, species = "PARAS"}, {level = 9, species = "METAPOD"} },
      { {level = 10, species = "WEEDLE"}, {level = 10, species = "BEEDRILL"} },
      { {level = 10, species = "CATERPIE"}, {level = 10, species = "BUTTERFREE"} },
      { {level = 13, species = "BUTTERFREE"}, {level = 13, species = "BEEDRILL"} },
      { {level = 18, species = "BUTTERFREE"}, {level = 18, species = "BEEDRILL"} },
      { {level = 18, species = "VENONAT"}, {level = 18, species = "SCYTHER"} },
      { {level = 18, species = "METAPOD"}, {level = 18, species = "CATERPIE"}, {level = 18, species = "VENONAT"} },
      { {level = 23, species = "VENONAT"}, {level = 23, species = "PINSIR"} },
      { {level = 21, species = "BUTTERFREE"}, {level = 21, species = "BEEDRILL"}, {level = 21, species = "SCYTHER"} },
      { {level = 6, species = "CATERPIE"}, {level = 6, species = "METAPOD"} },
    } },
    ["OPP_BURGLAR"] = { parties = {
      { {level = 29, species = "GROWLITHE"}, {level = 29, species = "VULPIX"} },
      { {level = 33, species = "GROWLITHE"} },
      { {level = 28, species = "VULPIX"}, {level = 28, species = "CHARMANDER"}, {level = 28, species = "PONYTA"} },
      { {level = 48, species = "FLAREON"}, {level = 48, species = "NINETALES"} },
      { {level = 51, species = "RAPIDASH"} },
      { {level = 54, species = "VULPIX"}, {level = 54, species = "GROWLITHE"} },
      { {level = 44, species = "PRIMEAPE"}, {level = 44, species = "MAGMAR"} },
      { {level = 43, species = "NINETALES"} },
      { {level = 44, species = "MACHOKE"}, {level = 44, species = "RAPIDASH"} },
    } },
    ["OPP_CHANNELER"] = { parties = {
      { {level = 22, species = "GASTLY"} },
      { {level = 24, species = "GASTLY"} },
      { {level = 23, species = "GASTLY"}, {level = 23, species = "GASTLY"} },
      { {level = 24, species = "GASTLY"} },
      { {level = 26, species = "GASTLY"} },
      { {level = 26, species = "VULPIX"} },
      { {level = 24, species = "HAUNTER"} },
      { {level = 27, species = "GASTLY"} },
      { {level = 27, species = "GASTLY"}, {level = 27, species = "VULPIX"} },
      { {level = 28, species = "GASTLY"}, {level = 28, species = "DROWZEE"} },
      { {level = 24, species = "GASTLY"} },
      { {level = 29, species = "HAUNTER"} },
      { {level = 24, species = "GASTLY"} },
      { {level = 28, species = "HAUNTER"}, {level = 28, species = "HYPNO"} },
      { {level = 24, species = "GASTLY"} },
      { {level = 30, species = "GASTLY"}, {level = 30, species = "NINETALES"} },
      { {level = 30, species = "MR_MIME"}, {level = 30, species = "GASTLY"} },
      { {level = 28, species = "VULPIX"}, {level = 28, species = "HAUNTER"} },
      { {level = 32, species = "GASTLY"}, {level = 32, species = "DROWZEE"}, {level = 32, species = "HAUNTER"} },
      { {level = 35, species = "HAUNTER"} },
      { {level = 33, species = "HYPNO"}, {level = 33, species = "HAUNTER"}, {level = 33, species = "NINETALES"} },
      { {level = 44, species = "HAUNTER"}, {level = 44, species = "NINETALES"} },
      { {level = 45, species = "HYPNO"} },
      { {level = 43, species = "HYPNO"}, {level = 43, species = "HAUNTER"}, {level = 43, species = "KADABRA"} },
    } },
    ["OPP_COOLTRAINER_F"] = { parties = {
      { {level = 29, species = "WEEPINBELL"}, {level = 29, species = "GLOOM"}, {level = 29, species = "IVYSAUR"} },
      { {level = 53, species = "DRAGONAIR"}, {level = 53, species = "GENGAR"}, {level = 53, species = "TAUROS"}, {level = 53, species = "NIDOQUEEN"} },
      { {level = 54, species = "WIGGLYTUFF"}, {level = 54, species = "CLEFABLE"}, {level = 54, species = "CHANSEY"}, {level = 57, species = "EEVEE"} },
      { {level = 46, species = "VILEPLUME"}, {level = 46, species = "BUTTERFREE"} },
      { {level = 53, species = "SEADRA"}, {level = 53, species = "DRAGONAIR"}, {level = 53, species = "VENUSAUR"}, {level = 53, species = "HYPNO"} },
      { {level = 45, species = "IVYSAUR"}, {level = 45, species = "VENUSAUR"} },
      { {level = 45, species = "NIDORINA"}, {level = 45, species = "NIDOQUEEN"} },
      { {level = 43, species = "PERSIAN"}, {level = 43, species = "NINETALES"}, {level = 43, species = "RAICHU"} },
    } },
    ["OPP_COOLTRAINER_M"] = { parties = {
      { {level = 52, species = "NIDOQUEEN"}, {level = 52, species = "NIDOKING"} },
      { {level = 52, species = "CHARIZARD"}, {level = 52, species = "MAGNETON"}, {level = 52, species = "TENTACRUEL"}, {level = 52, species = "RHYDON"} },
      { {level = 53, species = "NIDOKING"}, {level = 53, species = "CHARIZARD"}, {level = 53, species = "VILEPLUME"}, {level = 53, species = "SLOWBRO"} },
      { {level = 45, species = "KINGLER"}, {level = 45, species = "STARMIE"} },
      { {level = 53, species = "ELECTABUZZ"}, {level = 53, species = "SNORLAX"}, {level = 53, species = "SLOWBRO"}, {level = 53, species = "PORYGON"} },
      { {level = 44, species = "IVYSAUR"}, {level = 44, species = "WARTORTLE"}, {level = 44, species = "CHARMELEON"} },
      { {level = 49, species = "NIDOKING"} },
      { {level = 44, species = "KINGLER"}, {level = 44, species = "CLOYSTER"} },
      { {level = 53, species = "SANDSLASH"}, {level = 53, species = "MAROWAK"} },
      { {level = 51, species = "GOLEM"}, {level = 51, species = "ELECTRODE"}, {level = 51, species = "VICTREEBEL"} },
    } },
    ["OPP_CUE_BALL"] = { parties = {
      { {level = 28, species = "MACHOP"}, {level = 28, species = "WIGGLYTUFF"}, {level = 28, species = "MACHOP"} },
      { {level = 29, species = "MANKEY"}, {level = 29, species = "MACHOP"} },
      { {level = 31, species = "MACHOKE"} },
      { {level = 31, species = "PRIMEAPE"}, {level = 31, species = "WIGGLYTUFF"} },
      { {level = 32, species = "MACHOKE"}, {level = 32, species = "CLEFABLE"} },
      { {level = 34, species = "MACHOKE"} },
      { {level = 30, species = "MANKEY"}, {level = 30, species = "PRIMEAPE"}, {level = 30, species = "CLEFABLE"}, {level = 30, species = "MACHOKE"} },
      { {level = 32, species = "PRIMEAPE"}, {level = 32, species = "MACHOKE"} },
      { {level = 42, species = "CLOYSTER"}, {level = 42, species = "RHYDON"}, {level = 42, species = "TENTACRUEL"} },
    } },
    ["OPP_ENGINEER"] = { parties = {
      { {level = 21, species = "VOLTORB"}, {level = 21, species = "MAGNEMITE"} },
      { {level = 21, species = "MAGNEMITE"} },
      { {level = 18, species = "MAGNEMITE"}, {level = 18, species = "MACHOP"}, {level = 18, species = "MAGNEMITE"} },
    } },
    ["OPP_ERIKA"] = { parties = {
      { {level = 33, species = "TANGELA"}, {level = 34, species = "VICTREEBEL"}, {level = 31, species = "IVYSAUR"}, {level = 35, species = "VILEPLUME"} },
    } },
    ["OPP_FISHER"] = { parties = {
      { {level = 18, species = "GOLDEEN"}, {level = 18, species = "TENTACOOL"}, {level = 18, species = "GOLDEEN"} },
      { {level = 18, species = "TENTACOOL"}, {level = 18, species = "STARYU"}, {level = 18, species = "SHELLDER"} },
      { {level = 25, species = "GOLDEEN"}, {level = 25, species = "POLIWAG"}, {level = 25, species = "GOLDEEN"} },
      { {level = 26, species = "TENTACOOL"}, {level = 26, species = "GOLDEEN"} },
      { {level = 28, species = "SEAKING"} },
      { {level = 24, species = "POLIWAG"}, {level = 24, species = "SHELLDER"}, {level = 24, species = "GOLDEEN"}, {level = 24, species = "HORSEA"} },
      { {level = 40, species = "SEAKING"}, {level = 40, species = "GOLDEEN"}, {level = 40, species = "SEAKING"}, {level = 40, species = "SEAKING"} },
      { {level = 41, species = "SHELLDER"}, {level = 41, species = "CLOYSTER"} },
      { {level = 30, species = "MAGIKARP"}, {level = 38, species = "GYARADOS"}, {level = 38, species = "GYARADOS"}, {level = 38, species = "GYARADOS"}, {level = 38, species = "GYARADOS"}, {level = 40, species = "GYARADOS"} },
      { {level = 40, species = "SEAKING"}, {level = 40, species = "TENTACRUEL"} },
      { {level = 27, species = "MAGIKARP"}, {level = 27, species = "MAGIKARP"}, {level = 32, species = "GYARADOS"} },
    } },
    ["OPP_GAMBLER"] = { parties = {
      { {level = 19, species = "POLIWAG"}, {level = 19, species = "HORSEA"} },
      { {level = 19, species = "BELLSPROUT"}, {level = 19, species = "ODDISH"} },
      { {level = 19, species = "DROWZEE"}, {level = 19, species = "KADABRA"} },
      { {level = 19, species = "GROWLITHE"}, {level = 19, species = "VULPIX"} },
      { {level = 24, species = "POLIWAG"}, {level = 24, species = "POLIWAG"}, {level = 27, species = "POLIWHIRL"} },
      { {level = 22, species = "ONIX"}, {level = 22, species = "GEODUDE"}, {level = 22, species = "GRAVELER"} },
      { {level = 27, species = "GROWLITHE"}, {level = 27, species = "VULPIX"} },
    } },
    ["OPP_GENTLEMAN"] = { parties = {
      { {level = 18, species = "GROWLITHE"}, {level = 18, species = "GROWLITHE"} },
      { {level = 19, species = "NIDORAN_M"}, {level = 19, species = "NIDORAN_F"} },
      { {level = 22, species = "VOLTORB"}, {level = 22, species = "MAGNEMITE"} },
      { {level = 48, species = "PRIMEAPE"} },
      { {level = 18, species = "GROWLITHE"}, {level = 18, species = "PONYTA"} },
    } },
    ["OPP_GIOVANNI"] = { parties = {
      { {level = 29, species = "ONIX"}, {level = 31, species = "KANGASKHAN"}, {level = 30, species = "MAROWAK"}, {level = 32, species = "PERSIAN"} },
      { {level = 44, species = "KINGLER"}, {level = 44, species = "KANGASKHAN"}, {level = 45, species = "MACHOKE"}, {level = 44, species = "GOLEM"}, {level = 47, species = "PERSIAN"} },
      { {level = 53, species = "DUGTRIO"}, {level = 54, species = "NIDOQUEEN"}, {level = 55, species = "PERSIAN"}, {level = 54, species = "NIDOKING"}, {level = 55, species = "RHYDON"} },
    } },
    ["OPP_HIKER"] = { parties = {
      { {level = 10, species = "GEODUDE"}, {level = 10, species = "GEODUDE"}, {level = 10, species = "ONIX"} },
      { {level = 16, species = "MACHOP"}, {level = 16, species = "GEODUDE"} },
      { {level = 15, species = "GEODUDE"}, {level = 15, species = "ZUBAT"}, {level = 15, species = "MACHOP"}, {level = 15, species = "GEODUDE"} },
      { {level = 18, species = "ONIX"} },
      { {level = 24, species = "GEODUDE"}, {level = 24, species = "ONIX"} },
      { {level = 22, species = "GEODUDE"}, {level = 22, species = "MACHOP"}, {level = 22, species = "GEODUDE"} },
      { {level = 25, species = "ZUBAT"}, {level = 25, species = "ONIX"}, {level = 25, species = "GOLBAT"} },
      { {level = 27, species = "RHYHORN"}, {level = 27, species = "DUGTRIO"} },
      { {level = 24, species = "GEODUDE"}, {level = 24, species = "GEODUDE"}, {level = 24, species = "GRAVELER"} },
      { {level = 26, species = "GRAVELER"} },
      { {level = 23, species = "MACHOP"}, {level = 23, species = "ONIX"} },
      { {level = 24, species = "MACHOP"}, {level = 25, species = "MACHOKE"} },
      { {level = 24, species = "ONIX"}, {level = 24, species = "SANDSHREW"}, {level = 24, species = "ONIX"} },
      { {level = 24, species = "GEODUDE"}, {level = 25, species = "GRAVELER"} },
    } },
    ["OPP_JR_TRAINER_F"] = { parties = {
      { {level = 19, species = "SEEL"} },
      { {level = 16, species = "ODDISH"}, {level = 16, species = "BELLSPROUT"} },
      { {level = 16, species = "PIDGEY"}, {level = 16, species = "SPEAROW"}, {level = 16, species = "PIDGEY"} },
      { {level = 22, species = "BULBASAUR"} },
      { {level = 21, species = "ODDISH"}, {level = 21, species = "BELLSPROUT"}, {level = 21, species = "TANGELA"}, {level = 21, species = "PIDGEOTTO"} },
      { {level = 24, species = "MEOWTH"} },
      { {level = 25, species = "CLEFAIRY"}, {level = 25, species = "WIGGLYTUFF"} },
      { {level = 26, species = "PIDGEOTTO"}, {level = 26, species = "FARFETCHD"} },
      { {level = 23, species = "JIGGLYPUFF"}, {level = 23, species = "PIDGEOTTO"}, {level = 23, species = "MEOWTH"} },
      { {level = 24, species = "GLOOM"}, {level = 24, species = "IVYSAUR"} },
      { {level = 29, species = "BULBASAUR"}, {level = 29, species = "IVYSAUR"} },
      { {level = 28, species = "POLIWHIRL"}, {level = 28, species = "CLEFAIRY"}, {level = 28, species = "WEEPINBELL"}, {level = 28, species = "POLIWHIRL"}, {level = 28, species = "MEOWTH"} },
      { {level = 29, species = "POLIWHIRL"}, {level = 29, species = "SEAKING"} },
      { {level = 28, species = "TANGELA"}, {level = 28, species = "PERSIAN"} },
      { {level = 29, species = "POLIWHIRL"}, {level = 29, species = "SEADRA"} },
      { {level = 41, species = "SEAKING"}, {level = 41, species = "SEAKING"} },
      { {level = 24, species = "WEEPINBELL"}, {level = 24, species = "CLEFAIRY"} },
      { {level = 23, species = "MEOWTH"}, {level = 23, species = "WARTORTLE"}, {level = 23, species = "FEAROW"} },
      { {level = 23, species = "PIDGEOTTO"}, {level = 23, species = "RATICATE"}, {level = 23, species = "NIDORINA"}, {level = 23, species = "WEEPINBELL"} },
      { {level = 34, species = "PSYDUCK"}, {level = 34, species = "PERSIAN"}, {level = 34, species = "GOLDUCK"} },
      { {level = 36, species = "WEEPINBELL"}, {level = 36, species = "POLIWRATH"} },
      { {level = 38, species = "CLEFABLE"} },
      { {level = 35, species = "TANGELA"}, {level = 35, species = "PONYTA"}, {level = 35, species = "SANDSLASH"} },
      { {level = 40, species = "TENTACRUEL"}, {level = 40, species = "SEADRA"}, {level = 40, species = "DEWGONG"} },
      { {level = 19, species = "CUBONE"} },
    } },
    ["OPP_JR_TRAINER_M"] = { parties = {
      { {level = 9, species = "DIGLETT"}, {level = 9, species = "SANDSHREW"} },
      { {level = 15, species = "DIGLETT"}, {level = 15, species = "PSYDUCK"} },
      { {level = 18, species = "MANKEY"} },
      { {level = 20, species = "SQUIRTLE"} },
      { {level = 17, species = "MANKEY"}, {level = 17, species = "RATICATE"} },
      { {level = 18, species = "DIGLETT"}, {level = 18, species = "DIGLETT"}, {level = 18, species = "SANDSHREW"} },
      { {level = 21, species = "GROWLITHE"}, {level = 21, species = "CHARMANDER"} },
      { {level = 21, species = "RATICATE"}, {level = 21, species = "DIGLETT"}, {level = 21, species = "BELLSPROUT"}, {level = 21, species = "SANDSHREW"} },
      { {level = 29, species = "NIDORINA"}, {level = 29, species = "NIDORINO"} },
      { {level = 16, species = "HORSEA"}, {level = 16, species = "BELLSPROUT"} },
    } },
    ["OPP_JUGGLER"] = { parties = {
      { {level = 37, species = "KADABRA"}, {level = 37, species = "MR_MIME"} },
      { {level = 51, species = "POLIWRATH"}, {level = 51, species = "RHYDON"}, {level = 51, species = "FLAREON"}, {level = 51, species = "JOLTEON"} },
      { {level = 34, species = "BEEDRILL"}, {level = 34, species = "NIDOKING"}, {level = 34, species = "GOLBAT"}, {level = 34, species = "HAUNTER"} },
      { {level = 37, species = "TENTACRUEL"}, {level = 37, species = "MUK"} },
      { {level = 53, species = "OMASTAR"}, {level = 53, species = "ALAKAZAM"}, {level = 53, species = "RAICHU"}, {level = 53, species = "MR_MIME"} },
      { {level = 33, species = "HYPNO"} },
      { {level = 40, species = "HYPNO"} },
      { {level = 36, species = "WEEZING"}, {level = 36, species = "HYPNO"} },
    } },
    ["OPP_KOGA"] = { parties = {
      { {level = 42, species = "GOLBAT"}, {level = 42, species = "MUK"}, {level = 41, species = "TENTACRUEL"}, {level = 43, species = "VENOMOTH"} },
    } },
    ["OPP_LANCE"] = { parties = {
      { {level = 61, species = "DRAGONITE"}, {level = 60, species = "GYARADOS"}, {level = 60, species = "CHARIZARD"}, {level = 61, species = "AERODACTYL"}, {level = 62, species = "DRAGONITE"} },
    } },
    ["OPP_LASS"] = { parties = {
      { {level = 9, species = "PIDGEY"}, {level = 9, species = "PIDGEY"} },
      { {level = 10, species = "RATTATA"}, {level = 10, species = "NIDORAN_M"} },
      { {level = 14, species = "JIGGLYPUFF"} },
      { {level = 30, species = "PARASECT"}, {level = 30, species = "GLOOM"}, {level = 30, species = "PARASECT"} },
      { {level = 11, species = "ODDISH"}, {level = 11, species = "BELLSPROUT"} },
      { {level = 14, species = "CLEFAIRY"} },
      { {level = 16, species = "PIDGEY"}, {level = 16, species = "NIDORAN_F"} },
      { {level = 15, species = "JIGGLYPUFF"}, {level = 15, species = "ODDISH"} },
      { {level = 16, species = "WIGGLYTUFF"} },
      { {level = 16, species = "ODDISH"}, {level = 16, species = "PIDGEY"}, {level = 16, species = "ODDISH"} },
      { {level = 18, species = "PIDGEY"}, {level = 18, species = "NIDORINA"} },
      { {level = 21, species = "JIGGLYPUFF"} },
      { {level = 26, species = "WEEPINBELL"}, {level = 26, species = "NIDORINA"} },
      { {level = 27, species = "MEOWTH"}, {level = 27, species = "LICKITUNG"}, {level = 27, species = "NIDORINA"} },
      { {level = 24, species = "PIDGEOTTO"}, {level = 24, species = "RATICATE"}, {level = 24, species = "NIDORINA"}, {level = 24, species = "MEOWTH"}, {level = 24, species = "NIDORINO"} },
      { {level = 26, species = "CLEFAIRY"}, {level = 26, species = "CLEFABLE"} },
      { {level = 28, species = "GLOOM"}, {level = 28, species = "WEEPINBELL"} },
      { {level = 29, species = "PARASECT"}, {level = 29, species = "EXEGGCUTE"} },
      { {level = 6, species = "NIDORAN_F"}, {level = 6, species = "NIDORAN_M"} },
    } },
    ["OPP_LORELEI"] = { parties = {
      { {level = 56, species = "SLOWBRO"}, {level = 55, species = "CLOYSTER"}, {level = 55, species = "DEWGONG"}, {level = 56, species = "JYNX"}, {level = 57, species = "LAPRAS"} },
    } },
    ["OPP_LT_SURGE"] = { parties = {
      { {level = 22, species = "VOLTORB"}, {level = 23, species = "MAGNEMITE"}, {level = 24, species = "RAICHU"} },
    } },
    ["OPP_MISTY"] = { parties = {
      { {level = 19, species = "POLIWHIRL"}, {level = 18, species = "GOLDEEN"}, {level = 21, species = "STARMIE"} },
    } },
    ["OPP_POKEMANIAC"] = { parties = {
      { {level = 43, species = "MAGMAR"}, {level = 43, species = "JYNX"}, {level = 43, species = "LAPRAS"} },
      { {level = 27, species = "KANGASKHAN"} },
      { {level = 23, species = "SLOWPOKE"}, {level = 23, species = "LICKITUNG"}, {level = 23, species = "SLOWPOKE"} },
      { {level = 26, species = "CHARMELEON"}, {level = 26, species = "CUBONE"} },
      { {level = 25, species = "SLOWPOKE"} },
      { {level = 52, species = "VENUSAUR"}, {level = 52, species = "LAPRAS"}, {level = 52, species = "LICKITUNG"} },
      { {level = 25, species = "CUBONE"}, {level = 25, species = "SLOWPOKE"} },
    } },
    ["OPP_PROF_OAK"] = { parties = {
      { {level = 69, species = "TAUROS"}, {level = 70, species = "CHARIZARD"}, {level = 70, species = "VENUSAUR"}, {level = 70, species = "BLASTOISE"}, {level = 69, species = "SNORLAX"}, {level = 70, species = "NIDOKING"} },
      { {level = 78, species = "TAUROS"}, {level = 77, species = "ZAPDOS"}, {level = 77, species = "ARTICUNO"}, {level = 77, species = "MOLTRES"}, {level = 78, species = "SNORLAX"}, {level = 81, species = "NIDOKING"} },
    } },
    ["OPP_PSYCHIC_TR"] = { parties = {
      { {level = 42, species = "KADABRA"}, {level = 42, species = "SLOWBRO"}, {level = 42, species = "HYPNO"}, {level = 42, species = "KADABRA"} },
      { {level = 43, species = "MR_MIME"}, {level = 43, species = "KADABRA"} },
      { {level = 41, species = "VENOMOTH"}, {level = 41, species = "JYNX"}, {level = 41, species = "SLOWBRO"} },
      { {level = 45, species = "STARMIE"} },
    } },
    ["OPP_RIVAL1"] = { parties = {
      { {level = 5, species = "BULBASAUR"} },
      { {level = 9, species = "SPEAROW"}, {level = 8, species = "BULBASAUR"} },
      { {level = 18, species = "SPEAROW"}, {level = 15, species = "RATTATA"}, {level = 15, species = "BELLSPROUT"}, {level = 19, species = "BULBASAUR"} },
    } },
    ["OPP_RIVAL2"] = { parties = {
      { {level = 20, species = "RATICATE"}, {level = 22, species = "WEEPINBELL"}, {level = 21, species = "SANDSHREW"}, {level = 24, species = "IVYSAUR"} },
      { {level = 34, species = "FEAROW"}, {level = 32, species = "SHELLDER"}, {level = 32, species = "GROWLITHE"}, {level = 33, species = "KADABRA"}, {level = 35, species = "IVYSAUR"} },
      { {level = 34, species = "FEAROW"}, {level = 32, species = "MAGNEMITE"}, {level = 33, species = "KADABRA"}, {level = 32, species = "SHELLDER"}, {level = 35, species = "CHARMELEON"} },
      { {level = 34, species = "FEAROW"}, {level = 32, species = "VULPIX"}, {level = 33, species = "KADABRA"}, {level = 32, species = "SCYTHER"}, {level = 35, species = "WARTORTLE"} },
      { {level = 43, species = "PARASECT"}, {level = 44, species = "GYARADOS"}, {level = 43, species = "RHYDON"}, {level = 44, species = "ALAKAZAM"}, {level = 46, species = "VENUSAUR"} },
      { {level = 43, species = "ELECTABUZZ"}, {level = 44, species = "CLOYSTER"}, {level = 43, species = "DODRIO"}, {level = 44, species = "ALAKAZAM"}, {level = 46, species = "CHARIZARD"} },
      { {level = 43, species = "VICTREEBEL"}, {level = 44, species = "PORYGON"}, {level = 43, species = "PRIMEAPE"}, {level = 44, species = "ALAKAZAM"}, {level = 46, species = "BLASTOISE"} },
      { {level = 55, species = "VENUSAUR"}, {level = 53, species = "PIDGEOT"}, {level = 52, species = "MAGNETON"}, {level = 52, species = "MAROWAK"}, {level = 54, species = "ARCANINE"}, {level = 54, species = "ALAKAZAM"} },
      { {level = 54, species = "FEAROW"}, {level = 52, species = "MAGNETON"}, {level = 53, species = "GOLDUCK"}, {level = 54, species = "ALAKAZAM"}, {level = 52, species = "MAROWAK"}, {level = 55, species = "CHARIZARD"} },
      { {level = 53, species = "PIDGEOT"}, {level = 54, species = "MACHAMP"}, {level = 54, species = "ALAKAZAM"}, {level = 52, species = "NINETALES"}, {level = 52, species = "SCYTHER"}, {level = 55, species = "BLASTOISE"} },
    } },
    ["OPP_RIVAL3"] = { parties = {
      { {level = 63, species = "ALAKAZAM"}, {level = 60, species = "RHYDON"}, {level = 61, species = "GYARADOS"}, {level = 63, species = "ARCANINE"}, {level = 62, species = "MAGNETON"}, {level = 65, species = "VENUSAUR"} },
      { {level = 62, species = "MAGNETON"}, {level = 61, species = "DODRIO"}, {level = 63, species = "ALAKAZAM"}, {level = 60, species = "SANDSLASH"}, {level = 62, species = "CLOYSTER"}, {level = 65, species = "CHARIZARD"} },
      { {level = 60, species = "MACHAMP"}, {level = 61, species = "PIDGEOT"}, {level = 62, species = "NINETALES"}, {level = 62, species = "VICTREEBEL"}, {level = 63, species = "ALAKAZAM"}, {level = 65, species = "BLASTOISE"} },
    } },
    ["OPP_ROCKER"] = { parties = {
      { {level = 21, species = "VOLTORB"}, {level = 21, species = "VOLTORB"}, {level = 21, species = "VOLTORB"} },
      { {level = 29, species = "VOLTORB"}, {level = 29, species = "ELECTRODE"} },
    } },
    ["OPP_ROCKET"] = { parties = {
      { {level = 13, species = "RATTATA"}, {level = 13, species = "ZUBAT"} },
      { {level = 11, species = "SANDSHREW"}, {level = 11, species = "RATTATA"}, {level = 11, species = "ZUBAT"} },
      { {level = 12, species = "ZUBAT"}, {level = 12, species = "EKANS"} },
      { {level = 16, species = "RATICATE"} },
      { {level = 17, species = "MACHOP"}, {level = 17, species = "DROWZEE"} },
      { {level = 15, species = "EKANS"}, {level = 15, species = "ZUBAT"} },
      { {level = 23, species = "RATICATE"}, {level = 23, species = "GOLBAT"} },
      { {level = 25, species = "DROWZEE"}, {level = 25, species = "MACHOP"} },
      { {level = 26, species = "EKANS"}, {level = 26, species = "RATICATE"} },
      { {level = 25, species = "GRIMER"}, {level = 25, species = "KOFFING"}, {level = 25, species = "CUBONE"} },
      { {level = 26, species = "DROWZEE"}, {level = 26, species = "SANDSHREW"}, {level = 26, species = "RATICATE"} },
      { {level = 25, species = "GRIMER"}, {level = 25, species = "ARBOK"} },
      { {level = 24, species = "GOLBAT"}, {level = 24, species = "KOFFING"}, {level = 24, species = "GRIMER"}, {level = 24, species = "RATICATE"} },
      { {level = 26, species = "EKANS"}, {level = 26, species = "RATICATE"}, {level = 26, species = "DROWZEE"} },
      { {level = 27, species = "MACHOKE"}, {level = 27, species = "ARBOK"} },
      { {level = 23, species = "SANDSHREW"}, {level = 23, species = "EKANS"}, {level = 23, species = "SANDSLASH"} },
      { {level = 23, species = "EKANS"}, {level = 23, species = "SANDSHREW"}, {level = 23, species = "ARBOK"} },
      { {level = 26, species = "KOFFING"}, {level = 26, species = "GOLBAT"} },
      { {level = 25, species = "ZUBAT"}, {level = 25, species = "ZUBAT"}, {level = 25, species = "GOLBAT"} },
      { {level = 26, species = "KOFFING"}, {level = 26, species = "DROWZEE"} },
      { {level = 23, species = "ZUBAT"}, {level = 23, species = "RATICATE"}, {level = 23, species = "RATICATE"}, {level = 23, species = "ZUBAT"} },
      { {level = 26, species = "DROWZEE"}, {level = 26, species = "KOFFING"} },
      { {level = 39, species = "MAROWAK"}, {level = 39, species = "GOLBAT"} },
      { {level = 35, species = "GOLBAT"}, {level = 35, species = "RATICATE"}, {level = 35, species = "GOLBAT"}, {level = 35, species = "PINSIR"} },
      { {level = 38, species = "RATICATE"}, {level = 38, species = "HYPNO"}, {level = 38, species = "MUK"} },
      { {level = 39, species = "MACHOKE"}, {level = 39, species = "HYPNO"} },
      { {level = 38, species = "ARBOK"}, {level = 38, species = "VILEPLUME"}, {level = 38, species = "MAROWAK"} },
      { {level = 40, species = "TAUROS"} },
      { {level = 41, species = "HYPNO"} },
      { {level = 39, species = "MUK"}, {level = 39, species = "PRIMEAPE"} },
      { {level = 38, species = "GOLBAT"}, {level = 38, species = "VILEPLUME"}, {level = 38, species = "RATICATE"} },
      { {level = 37, species = "RATICATE"}, {level = 37, species = "ARBOK"}, {level = 37, species = "WEEZING"}, {level = 37, species = "GOLBAT"} },
      { {level = 39, species = "MAROWAK"}, {level = 39, species = "MAGMAR"} },
      { {level = 39, species = "SANDSLASH"}, {level = 39, species = "VILEPLUME"} },
      { {level = 37, species = "RATICATE"}, {level = 37, species = "TENTACRUEL"}, {level = 37, species = "GOLBAT"}, {level = 37, species = "RATICATE"} },
      { {level = 39, species = "VICTREEBEL"}, {level = 39, species = "GOLBAT"}, {level = 39, species = "WEEZING"} },
      { {level = 38, species = "HYPNO"}, {level = 38, species = "MUK"}, {level = 38, species = "MACHOKE"} },
      { {level = 38, species = "GOLBAT"}, {level = 38, species = "HYPNO"}, {level = 38, species = "RHYHORN"} },
      { {level = 43, species = "MACHOKE"} },
      { {level = 38, species = "RATICATE"}, {level = 38, species = "MUK"}, {level = 38, species = "GOLBAT"}, {level = 38, species = "MAROWAK"}, {level = 38, species = "ARBOK"} },
      { {level = 32, species = "CUBONE"}, {level = 32, species = "DROWZEE"}, {level = 32, species = "MAROWAK"} },
      { {level = 15, species = "EKANS"}, {level = 16, species = "MEOWTH"}, {level = 15, species = "KOFFING"} },
      { {level = 28, species = "KOFFING"}, {level = 29, species = "MEOWTH"}, {level = 28, species = "ARBOK"} },
      { {level = 33, species = "MEOWTH"}, {level = 31, species = "ARBOK"}, {level = 30, species = "LICKITUNG"}, {level = 31, species = "WEEZING"} },
      { {level = 42, species = "WEEZING"}, {level = 41, species = "LICKITUNG"}, {level = 42, species = "ARBOK"}, {level = 44, species = "MEOWTH"}, {level = 43, species = "VICTREEBEL"} },
      { {level = 16, species = "KOFFING"} },
      { {level = 27, species = "KOFFING"} },
      { {level = 29, species = "WEEZING"} },
      { {level = 33, species = "WEEZING"} },
    } },
    ["OPP_SABRINA"] = { parties = {
      { {level = 47, species = "JYNX"}, {level = 48, species = "HYPNO"}, {level = 49, species = "MR_MIME"}, {level = 48, species = "SLOWBRO"}, {level = 50, species = "ALAKAZAM"} },
    } },
    ["OPP_SAILOR"] = { parties = {
      { {level = 19, species = "MACHOP"}, {level = 19, species = "KRABBY"} },
      { {level = 18, species = "MACHOP"}, {level = 18, species = "TENTACOOL"} },
      { {level = 21, species = "SHELLDER"} },
      { {level = 18, species = "HORSEA"}, {level = 18, species = "SHELLDER"}, {level = 18, species = "TENTACOOL"} },
      { {level = 19, species = "KRABBY"}, {level = 19, species = "STARYU"} },
      { {level = 18, species = "HORSEA"}, {level = 18, species = "STARYU"}, {level = 18, species = "KRABBY"} },
      { {level = 20, species = "MACHOP"} },
      { {level = 24, species = "MAGNEMITE"} },
    } },
    ["OPP_SCIENTIST"] = { parties = {
      { {level = 34, species = "KOFFING"}, {level = 34, species = "VOLTORB"} },
      { {level = 37, species = "MUK"}, {level = 37, species = "WEEZING"}, {level = 37, species = "PORYGON"}, {level = 37, species = "WEEZING"} },
      { {level = 38, species = "MAGNETON"}, {level = 38, species = "ELECTRODE"}, {level = 38, species = "MAGNETON"} },
      { {level = 39, species = "ELECTRODE"}, {level = 39, species = "WEEZING"} },
      { {level = 41, species = "ELECTABUZZ"} },
      { {level = 36, species = "MAGNETON"}, {level = 36, species = "PORYGON"}, {level = 36, species = "WEEZING"}, {level = 36, species = "MAGNEMITE"} },
      { {level = 35, species = "VOLTORB"}, {level = 35, species = "STARYU"}, {level = 35, species = "ELECTRODE"}, {level = 35, species = "MAGNETON"}, {level = 35, species = "STARMIE"} },
      { {level = 39, species = "ELECTRODE"}, {level = 39, species = "MUK"} },
      { {level = 43, species = "PORYGON"} },
      { {level = 40, species = "MUK"}, {level = 40, species = "KABUTOPS"} },
      { {level = 40, species = "WEEZING"}, {level = 40, species = "OMASTAR"} },
      { {level = 45, species = "MAGNETON"}, {level = 45, species = "ARCANINE"}, {level = 45, species = "MUK"} },
      { {level = 46, species = "PORYGON"}, {level = 46, species = "ELECTRODE"} },
    } },
    ["OPP_SUPER_NERD"] = { parties = {
      { {level = 11, species = "MAGNEMITE"}, {level = 11, species = "VOLTORB"} },
      { {level = 12, species = "GRIMER"}, {level = 12, species = "VOLTORB"}, {level = 12, species = "MAGNEMITE"} },
      { {level = 26, species = "VOLTORB"}, {level = 26, species = "KOFFING"}, {level = 26, species = "VOLTORB"}, {level = 26, species = "MAGNEMITE"} },
      { {level = 27, species = "GRIMER"}, {level = 27, species = "PORYGON"}, {level = 27, species = "GRIMER"} },
      { {level = 28, species = "KOFFING"} },
      { {level = 22, species = "KOFFING"}, {level = 22, species = "MAGNEMITE"}, {level = 22, species = "WEEZING"} },
      { {level = 20, species = "MAGNEMITE"}, {level = 20, species = "MAGNEMITE"}, {level = 20, species = "KOFFING"}, {level = 20, species = "MAGNEMITE"} },
      { {level = 24, species = "MAGNEMITE"}, {level = 24, species = "VOLTORB"} },
      { {level = 49, species = "VULPIX"}, {level = 49, species = "NINETALES"} },
      { {level = 53, species = "PONYTA"}, {level = 53, species = "CHARMELEON"}, {level = 53, species = "VULPIX"}, {level = 53, species = "GROWLITHE"} },
      { {level = 52, species = "RAPIDASH"} },
      { {level = 50, species = "CHARMELEON"}, {level = 50, species = "FLAREON"} },
    } },
    ["OPP_SWIMMER"] = { parties = {
      { {level = 16, species = "HORSEA"}, {level = 16, species = "SHELLDER"} },
      { {level = 43, species = "TENTACRUEL"}, {level = 43, species = "CLOYSTER"} },
      { {level = 40, species = "SEAKING"}, {level = 40, species = "SEADRA"}, {level = 40, species = "STARMIE"} },
      { {level = 42, species = "POLIWRATH"}, {level = 42, species = "SEADRA"} },
      { {level = 41, species = "SEADRA"}, {level = 41, species = "TENTACRUEL"}, {level = 41, species = "GYARADOS"} },
      { {level = 41, species = "SEAKING"}, {level = 41, species = "SLOWBRO"}, {level = 41, species = "GOLDUCK"} },
      { {level = 45, species = "SEADRA"} },
      { {level = 40, species = "TENTACRUEL"}, {level = 40, species = "TENTACRUEL"}, {level = 40, species = "STARMIE"}, {level = 40, species = "SEADRA"}, {level = 40, species = "TENTACRUEL"} },
      { {level = 42, species = "KINGLER"}, {level = 42, species = "CLOYSTER"} },
      { {level = 45, species = "GYARADOS"} },
      { {level = 42, species = "SEADRA"}, {level = 42, species = "GYARADOS"}, {level = 42, species = "SEADRA"} },
      { {level = 43, species = "SEADRA"}, {level = 43, species = "TENTACRUEL"} },
      { {level = 47, species = "STARMIE"} },
      { {level = 44, species = "TENTACRUEL"}, {level = 44, species = "BLASTOISE"} },
      { {level = 44, species = "POLIWHIRL"}, {level = 44, species = "KINGLER"}, {level = 44, species = "SEADRA"} },
    } },
    ["OPP_TAMER"] = { parties = {
      { {level = 36, species = "SANDSLASH"}, {level = 36, species = "ARBOK"} },
      { {level = 35, species = "ARBOK"}, {level = 35, species = "NIDOQUEEN"}, {level = 35, species = "ARBOK"} },
      { {level = 55, species = "RHYHORN"} },
      { {level = 53, species = "ARBOK"}, {level = 53, species = "TAUROS"} },
      { {level = 53, species = "TANGELA"}, {level = 53, species = "SANDSLASH"}, {level = 53, species = "LICKITUNG"}, {level = 53, species = "ARBOK"} },
      { {level = 42, species = "RHYHORN"}, {level = 42, species = "PRIMEAPE"}, {level = 42, species = "ARBOK"}, {level = 42, species = "TAUROS"} },
    } },
    ["OPP_YOUNGSTER"] = { parties = {
      { {level = 11, species = "RATTATA"}, {level = 11, species = "EKANS"} },
      { {level = 14, species = "SPEAROW"} },
      { {level = 10, species = "RATTATA"}, {level = 10, species = "SANDSHREW"}, {level = 10, species = "ZUBAT"} },
      { {level = 14, species = "RATTATA"}, {level = 14, species = "EKANS"}, {level = 14, species = "ZUBAT"} },
      { {level = 16, species = "RATTATA"}, {level = 16, species = "SPEAROW"} },
      { {level = 17, species = "SLOWPOKE"} },
      { {level = 16, species = "EKANS"}, {level = 16, species = "SANDSHREW"} },
      { {level = 21, species = "NIDORINO"} },
      { {level = 21, species = "EKANS"} },
      { {level = 19, species = "SANDSHREW"}, {level = 19, species = "ZUBAT"} },
      { {level = 17, species = "RATTATA"}, {level = 17, species = "RATTATA"}, {level = 20, species = "RATICATE"} },
      { {level = 18, species = "NIDORAN_M"}, {level = 18, species = "NIDORINO"} },
      { {level = 17, species = "SPEAROW"}, {level = 17, species = "RATTATA"}, {level = 17, species = "RATTATA"}, {level = 17, species = "SPEAROW"} },
      { {level = 28, species = "SANDSHREW"} },
    } },
  },

  -- Rival early-battle route variants.  Battles 1-4 (Oak's Lab, Route 22,
  -- Cerulean, S.S. Anne) use fixed party indexes in the engine's Yellow
  -- scripts, so the Eevee slot there is replaced by the route's starter
  -- line stage (base through S.S. Anne, then final from Silph Co. on).
  -- The trainer.party hook in main.lua swaps in the variant matching the
  -- player's current route (save.rivalStarter: 1 JOLTEON / 2 FLAREON /
  -- 3 VAPOREON): Bulbasaur line for Jolteon, Charmander line for Flareon,
  -- Squirtle line for Vaporeon.
  rivalVariants = {
    ["OPP_RIVAL1"] = {
      [1] = {
        [1] = { {level = 5, species = "BULBASAUR"} },
        [2] = { {level = 5, species = "CHARMANDER"} },
        [3] = { {level = 5, species = "SQUIRTLE"} },
      },
      [2] = {
        [1] = { {level = 9, species = "SPEAROW"}, {level = 8, species = "BULBASAUR"} },
        [2] = { {level = 9, species = "SPEAROW"}, {level = 8, species = "CHARMANDER"} },
        [3] = { {level = 9, species = "SPEAROW"}, {level = 8, species = "SQUIRTLE"} },
      },
      [3] = {
        [1] = { {level = 18, species = "SPEAROW"}, {level = 15, species = "RATTATA"}, {level = 15, species = "BELLSPROUT"}, {level = 19, species = "BULBASAUR"} },
        [2] = { {level = 18, species = "SPEAROW"}, {level = 15, species = "RATTATA"}, {level = 15, species = "BELLSPROUT"}, {level = 19, species = "CHARMANDER"} },
        [3] = { {level = 18, species = "SPEAROW"}, {level = 15, species = "RATTATA"}, {level = 15, species = "BELLSPROUT"}, {level = 19, species = "SQUIRTLE"} },
      },
    },
    ["OPP_RIVAL2"] = {
      [1] = {
        [1] = { {level = 20, species = "RATICATE"}, {level = 22, species = "WEEPINBELL"}, {level = 21, species = "SANDSHREW"}, {level = 24, species = "IVYSAUR"} },
        [2] = { {level = 20, species = "RATICATE"}, {level = 22, species = "WEEPINBELL"}, {level = 21, species = "SANDSHREW"}, {level = 24, species = "CHARMELEON"} },
        [3] = { {level = 20, species = "RATICATE"}, {level = 22, species = "WEEPINBELL"}, {level = 21, species = "SANDSHREW"}, {level = 24, species = "WARTORTLE"} },
      },
    },
  },
}
