-- Generated by mod-fixer for Gen1Recomp
-- Ships no ROM-derived pixels; legally derives art from the player's imported cache.

local DERIVED_ASSETS = {
  { source = "battle/trainers/jessie_james.png", dest = "battle/trainers/jessie_james.png" },
  { source = "sprites/james.png", dest = "sprites/james.png" },
  { source = "sprites/jessie.png", dest = "sprites/jessie.png" },
}

return function(ctx)
  for _, item in ipairs(DERIVED_ASSETS) do
    -- Derived only if the player has imported the required base game
    if ctx.exists(item.source) then
      local img = ctx.readImage(item.source)
      ctx.writeImage(img, item.dest)
    end
  end
end
